### ISSUE TITLE
files not indexing

### ISSUE THREAD

**Issue by Divytech** [Rishikesh-Sharma09/Auto-Filter-Bot#4]
'Bot' object has no attribute 'listen'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 344, in handler_worker
    await handler.callback(self.client, *args)
  File "/Auto-Filter-Bot/plugins/index.py", line 35, in send_for_index
    msg = await bot.listen(chat_id=message.chat.id, user_id=message.from_user.id)
                ^^^^^^^^^^

**Comment by Divytech** [comment]
> Update requirements.txt file and replace pyrogram to pyrofork

But what to do with pyrogram.error and many more pyrogram attributes?

**Comment by Rishikesh-Sharma09** [comment]
@Divytech Check my requirements.txt file use that pyrogram forked library .
